baseurl: https://vuptime.io
copyright: Ludovic Rivallain and blog co-authors
pagination:
  pagerSize: 10
theme: hugo-clarity
service:
  disqus:
    shortname: lri-ovh
taxonomies:
  category: categories
  tag: tags
  series: series
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"