twitter: '@vuptimeio'
largeTwitterCard: false
introDescription: >
  A cloud builders blog: Virtualization, Cloud Computing, VMware, Kubernetes, Infra-as-code…
  ![vExpert](/images/vexpert.png)
ga_analytics: UA-5631150-7
numberOfTagsShown: 15
fallBackOgImage: logos/favicon_500px.png
codeMaxLines: 30
codeLineNumbers: false
enableMathNotation: false
mainSections:
  - post
centerLogo: false
logo: logos/nobg_700px.png
figurePositionShow: false
figurePositionLabel: Figure
mobileNavigation: left
enforceLightMode: true
languageMenuName: "\U0001F310"
iconsDir: icons/
author:
  photo: icons/favicon_500px.png
#   homepage: https://ludovic.rivallain.fr
#  name: Ludovic Rivallain
customCSS:
- css/custom.css
# Copyrighted since
since: 2014
footerLogo: icons/favicon.png